// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LoginCredential struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID              string `json:"id"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	OtpCode         string `json:"otp_code"`
	Role            string `json:"role"`
	Status          string `json:"status"`
	IsEmailVerified bool   `json:"isEmailVerified"`
	OtpExpireTime   string `json:"otp_expire_time"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
	DeletedAt       string `json:"deletedAt"`
}

type UserSignUpDetail struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
